---

  - name: create alarms
    ec2_metric_alarm:
      state: present
      region: "{{ asg_deploy_aws_region }}"
      name: "{{ asg_deploy_uuid }}-{{item.name}}"
      metric: "{{item.alarm.metric}}"
      namespace: "{{item.alarm.namespace}}"
      statistic: "{{item.alarm.statistic}}"
      comparison: "{{item.alarm.comparison}}"
      threshold: "{{item.alarm.threshold}}"
      period: "{{item.alarm.period}}"
      evaluation_periods: "{{item.alarm.evaluation_periods}}"
      unit: "{{item.alarm.unit}}"
      description: "{{item.alarm.description}}"
      dimensions: 
        AutoScalingGroupName: "{{ asg_deploy_uuid }}"
      alarm_actions: "{{item.alarm.actions}}"
    with_items: 
      - "{{asg_deploy_cloudwatch_alarms}}"
    tags: alarms
